version: 'yml-{build}'
os: Windows Server 2012
install:
  - cmd: choco install sbt
  - cmd: refreshenv
  - cmd: sbt update
environment:
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
build_script:
  - cmd: 'ECHO Global / publishTo := Some(Resolver.file("artifact", file("""C:\projects\string-context-parser-combinator\publish"""))) >publish-location.sbt'
  - cmd: 'sbt compile publish'
test_script:
  - cmd: 'sbt test'
artifacts:
  - path: publish
    name: sbt_publish_directory
