version: 'yml-{build}'
image: Visual Studio 2022
install:
  - cmd: choco install sbt
  - cmd: refreshenv
  - cmd: sbt update
environment:
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
build_script:
  - cmd: 'sbt compile publishLocal'
  - cmd: 'move C:\Users\appveyor\.ivy2\local C:\projects\string-context-parser-combinator\publish'
test_script:
  - cmd: 'sbt test'
artifacts:
  - path: publish
    name: sbt_publish_directory
