name: publish-ghpages
on:
  push:
    branches:
      - main
jobs:
  ghpages_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'sbt'
    - name: Configure git user and sbt remote repo
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        echo 'Global / git.remoteRepo := "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"' >gitRemoteRepo.sbt
    - name: ghpagesPushSite
      run: sbt ghpagesPushSite
