name: publish-ghpages
on:
  push:
    branches:
      - master
jobs:
  ghpages_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache ivy modules
      uses: actions/cache@v2
      env:
        cache-name: cache-ivy-modules
      with:
        path: ~/.ivy2
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.sbt') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Configuration
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        echo 'Global / git.remoteRepo := "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"' >gitRemoteRepo.sbt
    - name: sbt update
      run: sbt update
    - name: publish
      run: sbt ghpagesPushSite
