name: publish-github
on:
  push:
    tags:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: publish
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'
        cache: 'sbt'
    - name: Configure sbt publishTo
      run: |
        echo 'Global / publishTo := Some("Github Package Repository" at "https://maven.pkg.github.com/rayrobdod/string-context-parser-combinator")' >publish-location.sbt
        echo 'Global / publishMavenStyle := true' >>publish-location.sbt
        echo 'Global / credentials += Credentials("GitHub Package Registry", "maven.pkg.github.com", "rayrobdod", sys.env("GITHUB_TOKEN"))' >>publish-location.sbt
    - name: sbt publish
      run: sbt publish
