name: publish-github
on:
  push:
    tags:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: publish
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup sbt
        run: |
          echo Global \/ publishTo \:\= Some\(\"Github Package Repository\" at \"https://maven.pkg.github.com/rayrobdod/string-context-parser-combinator\"\) >publish-location.sbt
          echo Global \/ publishMavenStyle \:\= true >>publish-location.sbt
          echo Global \/ credentials \+\= Credentials\(\"GitHub Package Registry\", \"maven.pkg.github.com\", \"rayrobdod\", sys.env\(\"GITHUB_TOKEN\"\)\) >>publish-location.sbt
      - name: sbt update
        run: sbt update
      - name: sbt publish
        run: sbt publish
