name: publish-artifact
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: publish
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup sbt
        run: |
          echo Global / publishTo \:\= Some\(Resolver.file\(\"artifact\", file\(\"./publish/\"\)\)\) >publish-location.sbt
      - name: sbt update
        run: sbt update
      - name: sbt publish
        run: sbt publish
      - name: Archive published
        uses: actions/upload-artifact@v1
        with:
          name: publish
          path: publish
