name: Check
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest]
        java: [ 8, 11, 17 ]
    runs-on: ${{ matrix.os }}
    name: Test-${{ matrix.os }}-${{ matrix.java }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        cache: 'sbt'
    - name: sbt Test/compile
      run: sbt Test/compile
    - name: sbt test
      run: sbt test
  publish-artifact:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 8 ]
    runs-on: ${{ matrix.os }}
    name: Artifact-${{ matrix.os }}-${{ matrix.java }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        cache: 'sbt'
    - name: Configure sbt publishTo
      run: |
        echo 'Global / publishTo := Some(Resolver.file("artifact", file("./publish/")))' >publish-location.sbt
    - name: publish to directory
      run: sbt publish
    - name: upload directory
      uses: actions/upload-artifact@v3
      with:
        name: publish-${{ matrix.os }}-${{ matrix.java }}
        path: publish
