name: Check
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest]
        java: [ 8, 17, 25 ]
    runs-on: ${{ matrix.os }}
    name: Test-${{ matrix.os }}-${{ matrix.java }}
    steps:
    - uses: actions/checkout@v5
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        apps: sbt
        jvm: zulu:${{matrix.java}}
    - name: set sbt settings
      run: echo "Global / parallelExecution := false">parallelExecution.sbt
    - name: sbt test
      run: sbt test
  mima:
    if: false
    needs: test
    runs-on: ubuntu-latest
    name: MigrationManager
    steps:
    - uses: actions/checkout@v5
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        apps: sbt
        jvm: zulu:8
    - name: sbt mimaReportBinaryIssues
      run: sbt mimaReportBinaryIssues
    - name: sbt tastyMiMaReportIssues
      run: sbt tastyMiMaReportIssues
  publish-artifact:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 8 ]
    runs-on: ${{ matrix.os }}
    name: Artifact-${{ matrix.os }}-${{ matrix.java }}
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        apps: sbt
        jvm: zulu:${{matrix.java}}
    - name: publishLocal
      run: sbt publishLocal
    - name: move local publish to somewhere upload-artifact can reach
      run: mv ~/.ivy2/local ./publish
    - name: upload directory
      uses: actions/upload-artifact@v4
      with:
        name: publish-${{ matrix.os }}-${{ matrix.java }}
        path: publish
