name: Check
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest]
        java: [ 8, 17, 21 ]
    runs-on: ${{ matrix.os }}
    name: Test-${{ matrix.os }}-${{ matrix.java }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        cache: 'sbt'
    - name: sbt Test/compile
      run: sbt Test/compile
    - name: sbt test
      run: sbt test
  publish-artifact:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 8 ]
    runs-on: ${{ matrix.os }}
    name: Artifact-${{ matrix.os }}-${{ matrix.java }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        cache: 'sbt'
    - name: publishLocal
      run: sbt publishLocal
    - name: move local publish to somewhere upload-artifact can reach
      run: mv ~/.ivy2/local ./publish
    - name: upload directory
      uses: actions/upload-artifact@v4
      with:
        name: publish-${{ matrix.os }}-${{ matrix.java }}
        path: publish
